num1 =input("enter an integer:") 
num2 =input("enter an integer value: ")

print (int(num1)+int(num2))
print (int(num1)-int(num2))
print (int(num1)*int(num2))
print (int(num1)%int(num2))
print (int(num1)/int(num2))
print (int(num1)//int(num2))
print(num1>num2)
print(num1<num2)
print(num1>=num2)
print(num1<=num2)
print(num1==num2)
print(num1!=num2)
print(num1>num2 and num1<num2)
print(num1<num2 and num1>num2 )
print(num1>num2  or num1<num2 )
print ( num1<num2 or num1>num2 )
print(not(num1>num2 and num1<num2))
print(not(num1>num2))
print(not( num1<num2))
print(not(num1>num2 or num1<num2))
print(num1 is num2)#Identity operator used to compare to values to determine if they point to the same object there are 2 types of identify operator in Pythonis and is not The ease operator returns to if both the operands point to the same object the Is not operator returns true if both operand do not point to the same object
print(num1 is not num2)
